name: Unit Tests

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  native_tests:
    name: Logic Tests (Native)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache Pip/PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio
          key: ${{ runner.os }}-pio-tests-${{ hashFiles('**/platformio.ini') }}

      - name: Install PlatformIO
        run: pip install --upgrade platformio

      - name: Run Unit Tests
        run: pio test -e native -v